name: Comment

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  comment:
    - uses: marocchino/sticky-pull-request-comment@v2
      with:
        message: |
          Making a comment
