name: Test

on: [push, pull_request]

jobs:
  echo:
    runs-on: ubuntu-24.04
    steps:
      - name: echo test
        run: |
          echo "test"
  echo_oops:
    runs-on: ubuntu-24.04
    steps:
      - name: echo token
        run: |
          echo "Token: ${GITHUB_TOKEN}"
